// frontend/src/components/TarotView.vue
<template>
  <view class="tarot-wrap">
    <view class="head">
      <view v-if="view !== 'main'" class="icon-btn" @click="view = 'main'">←</view>
      <view v-else class="spacer"></view>

      <view class="head-center">
        <text class="title">塔罗倾听</text>
        <text class="sub">让潜意识为你指引方向</text>
      </view>

      <view v-if="view === 'main'" class="icon-btn" @click="view = 'history'">🕘</view>
      <view v-else class="spacer"></view>
    </view>

    <view v-if="view === 'main'" class="main-view">
      <view v-if="step === 'question'" class="glass-panel panel">
        <text class="label">你现在有什么困惑或心事？</text>
        <textarea
          v-model="question"
          class="textarea"
          placeholder="例如：我最近对工作感到很迷茫，不知道该不该换环境..."
        />
        <button class="primary-btn" :disabled="!question.trim() || isLoading" :loading="isLoading" @click="handleStartDraw">
          {{ isLoading ? '大福正在思考牌阵...' : '告诉大福' }}
        </button>
      </view>

      <view v-if="step === 'shuffling'" class="shuffle-wrap">
        <view class="shuffle-cards">
          <view v-for="i in 3" :key="i" :class="['shuffle-card', `card-${i}`]">✧</view>
        </view>
        <text class="shuffle-text">大福正在为你洗牌...</text>
      </view>

      <view v-if="step === 'draw' && spread" class="draw-wrap">
        <view class="draw-head">
          <text class="draw-title">大福为你选择了：{{ spread.name }}</text>
          <text class="draw-sub">请深呼吸，凭直觉抽取 {{ spread.count }} 张牌（{{ selectedIndices.length }}/{{ spread.count }}）</text>
        </view>

        <view class="card-grid">
          <view
            v-for="idx in 22"
            :key="idx"
            :class="['deck-card', selectedIndices.includes(idx - 1) ? 'deck-card-selected' : '']"
            @click="handleSelectCard(idx - 1)"
          >
            ✧
          </view>
        </view>

        <view v-if="isLoading" class="loading-more">
          <view class="spinner"></view>
          <text>大福正在解读牌意...</text>
        </view>
      </view>
    </view>

    <scroll-view v-if="view === 'history'" class="history-view" scroll-y>
      <view v-if="history.length === 0" class="empty">暂无占卜记录</view>
      <view v-for="item in history" :key="item.id" class="glass-panel history-item" @click="openHistoryItem(item)">
        <view class="history-top">
          <text class="history-date">{{ item.date }}</text>
          <text class="history-tag">{{ item.spread.name }}</text>
        </view>
        <text class="history-question">{{ item.question }}</text>
      </view>
    </scroll-view>

    <view v-if="view === 'reading' && currentReading" class="reading-view">
      <scroll-view class="reading-scroll" scroll-y>
        <view class="glass-panel reading-card">
          <view class="reading-question-box">
            <text class="small-muted">你的问题</text>
            <text class="reading-question">{{ currentReading.question }}</text>
          </view>

          <text class="reading-title">大福的解读</text>

          <view class="tarot-cards">
            <view v-for="(card, idx) in currentReading.cards" :key="`${card}-${idx}`" class="tarot-card-item">
              <view class="mini-card">✨</view>
              <view>
                <text class="mini-pos">{{ currentReading.spread.positions[idx] }}</text>
                <text class="mini-name">{{ card }}</text>
              </view>
            </view>
          </view>

          <text class="reading-text pre">{{ currentReading.reading }}</text>
        </view>

        <view
          v-for="(msg, idx) in currentReading.chatHistory"
          :key="`msg-${idx}`"
          :class="['chat-row', msg.role === 'user' ? 'chat-row-user' : 'chat-row-model']"
        >
          <view :class="['chat-bubble', msg.role === 'user' ? 'chat-user' : 'glass-panel']">
            <text class="chat-text pre">{{ msg.content }}</text>
          </view>
        </view>

        <view v-if="isChatting" class="chat-row chat-row-model">
          <view class="glass-panel chat-bubble">
            <text class="chat-text">大福正在思考...</text>
          </view>
        </view>
      </scroll-view>

      <view class="chat-input-wrap">
        <input
          v-model="followUp"
          class="chat-input"
          placeholder="继续向大福提问..."
          @confirm="handleSendFollowUp"
        />
        <view class="send-btn" @click="handleSendFollowUp">➤</view>
      </view>
    </view>
  </view>
</template>

<script setup>
import { onMounted, ref } from 'vue';
import { determineTarotSpread, generateTarotFollowUp, generateTarotReading } from '../utils/api';

const TAROT_DECK = [
  '愚者', '魔术师', '女祭司', '皇后', '皇帝', '教皇',
  '恋人', '战车', '力量', '隐士', '命运之轮', '正义',
  '倒吊人', '死神', '节制', '恶魔', '高塔', '星星',
  '月亮', '太阳', '审判', '世界'
];

const view = ref('main');
const step = ref('question');
const question = ref('');
const spread = ref(null);
const selectedIndices = ref([]);

const currentReading = ref(null);
const history = ref([]);

const followUp = ref('');
const isChatting = ref(false);
const isLoading = ref(false);

onMounted(() => {
  const saved = uni.getStorageSync('tarot_history');
  if (saved) {
    history.value = saved;
  }
});

function saveHistory(next) {
  history.value = next;
  uni.setStorageSync('tarot_history', next);
}

async function handleStartDraw() {
  if (!question.value.trim()) return;
  isLoading.value = true;
  try {
    const spreadResult = await determineTarotSpread(question.value);
    spread.value = spreadResult;
    step.value = 'shuffling';
    setTimeout(() => {
      step.value = 'draw';
    }, 1600);
  } catch (error) {
    uni.showToast({ title: '暂时无法连接，请稍后再试', icon: 'none' });
  } finally {
    isLoading.value = false;
  }
}

async function handleSelectCard(index) {
  if (selectedIndices.value.includes(index) || !spread.value) return;

  const newSelected = [...selectedIndices.value, index];
  selectedIndices.value = newSelected;

  if (newSelected.length === spread.value.count) {
    const finalCards = [...TAROT_DECK].sort(() => 0.5 - Math.random()).slice(0, spread.value.count);

    isLoading.value = true;
    try {
      const reading = await generateTarotReading(question.value, spread.value, finalCards);
      const newItem = {
        id: `${Date.now()}`,
        date: new Date().toLocaleString('zh-CN'),
        question: question.value,
        spread: spread.value,
        cards: finalCards,
        reading,
        chatHistory: []
      };

      currentReading.value = newItem;
      saveHistory([newItem, ...history.value]);
      view.value = 'reading';

      step.value = 'question';
      question.value = '';
      spread.value = null;
      selectedIndices.value = [];
    } catch (error) {
      uni.showToast({ title: '解读失败，请稍后再试', icon: 'none' });
    } finally {
      isLoading.value = false;
    }
  }
}

async function handleSendFollowUp() {
  if (!followUp.value.trim() || !currentReading.value || isChatting.value) return;

  const userMsg = followUp.value;
  followUp.value = '';
  isChatting.value = true;

  const contextHistory = [
    {
      role: 'user',
      content: `我之前问了这个问题：“${currentReading.value.question}”。抽到的牌是：${currentReading.value.cards.join(', ')}。你的解读是：${currentReading.value.reading}`
    },
    { role: 'model', content: '我记得。请问你还有什么想深入了解的吗？' },
    ...currentReading.value.chatHistory
  ];

  const updatedReading = {
    ...currentReading.value,
    chatHistory: [...currentReading.value.chatHistory, { role: 'user', content: userMsg }]
  };
  currentReading.value = updatedReading;

  try {
    const reply = await generateTarotFollowUp(contextHistory, userMsg);
    const finalReading = {
      ...updatedReading,
      chatHistory: [...updatedReading.chatHistory, { role: 'model', content: reply }]
    };
    currentReading.value = finalReading;
    saveHistory(history.value.map((h) => (h.id === finalReading.id ? finalReading : h)));
  } catch (error) {
    uni.showToast({ title: '追问失败，请稍后再试', icon: 'none' });
  } finally {
    isChatting.value = false;
  }
}

function openHistoryItem(item) {
  currentReading.value = item;
  view.value = 'reading';
}
</script>

<style scoped lang="scss">
.tarot-wrap { min-height: 100%; display: flex; flex-direction: column; }
.head { display: flex; justify-content: space-between; align-items: center; margin-top: 8rpx; margin-bottom: 16rpx; }
.icon-btn, .spacer { width: 64rpx; height: 64rpx; display: flex; justify-content: center; align-items: center; color: #3a5358; }
.head-center { text-align: center; }
.title { display: block; color: #3a5358; font-size: 34rpx; font-weight: 600; }
.sub { display: block; margin-top: 4rpx; color: #6b8287; font-size: 22rpx; }
.glass-panel { background: rgba(255,255,255,0.62); border: 1rpx solid rgba(255,255,255,0.82); box-shadow: 0 12rpx 32rpx rgba(140,133,123,0.08); }
.panel { border-radius: 28rpx; padding: 24rpx; }
.label { display: block; color: #3a5358; font-size: 26rpx; margin-bottom: 14rpx; }
.textarea { width: 100%; height: 240rpx; box-sizing: border-box; border: 1rpx solid rgba(255,255,255,0.7); border-radius: 16rpx; background: rgba(255,255,255,0.45); color: #2c3e42; padding: 16rpx; font-size: 27rpx; }
.primary-btn { margin-top: 18rpx; background: #8ba89f; color: #fff; border-radius: 16rpx; font-size: 27rpx; }
.primary-btn::after { border: 0; }
.shuffle-wrap { min-height: 640rpx; display: flex; flex-direction: column; justify-content: center; align-items: center; }
.shuffle-cards { width: 180rpx; height: 260rpx; position: relative; }
.shuffle-card { position: absolute; inset: 0; background: rgba(255,255,255,0.65); border: 1rpx solid rgba(139,168,159,0.45); border-radius: 16rpx; display: flex; justify-content: center; align-items: center; color: rgba(92,122,125,0.55); font-size: 38rpx; }
.card-1 { transform: translateX(-20rpx) rotate(-6deg); }
.card-2 { transform: translateX(0) rotate(0); }
.card-3 { transform: translateX(20rpx) rotate(6deg); }
.shuffle-text { margin-top: 18rpx; color: #5c7a7d; font-size: 24rpx; }
.draw-wrap { min-height: 640rpx; }
.draw-head { text-align: center; margin-bottom: 18rpx; }
.draw-title { display: block; color: #3a5358; font-size: 26rpx; }
.draw-sub { display: block; margin-top: 6rpx; color: #6b8287; font-size: 22rpx; }
.card-grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 10rpx; }
.deck-card { aspect-ratio: 2/3; border-radius: 12rpx; background: rgba(255,255,255,0.62); border: 1rpx solid rgba(255,255,255,0.6); display: flex; justify-content: center; align-items: center; color: rgba(92,122,125,0.45); }
.deck-card-selected { background: rgba(139,168,159,0.2); border-color: #8ba89f; opacity: 0.6; }
.loading-more { margin-top: 14rpx; display: flex; justify-content: center; align-items: center; gap: 10rpx; color: #5c7a7d; font-size: 22rpx; }
.spinner { width: 28rpx; height: 28rpx; border-radius: 999rpx; border: 3rpx solid rgba(255,255,255,0.6); border-top-color: #8ba89f; animation: spin 1s linear infinite; }
.history-view { flex: 1; }
.empty { margin-top: 120rpx; text-align: center; color: #6b8287; font-size: 24rpx; }
.history-item { border-radius: 22rpx; padding: 18rpx; margin-bottom: 12rpx; }
.history-top { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 8rpx; }
.history-date { color: #6b8287; font-size: 20rpx; }
.history-tag { background: rgba(139,168,159,0.16); color: #3a5358; font-size: 20rpx; border-radius: 10rpx; padding: 4rpx 12rpx; }
.history-question { color: #2c3e42; font-size: 24rpx; line-height: 1.5; }
.reading-view { flex: 1; min-height: 0; display: flex; flex-direction: column; }
.reading-scroll { flex: 1; min-height: 0; }
.reading-card { border-radius: 26rpx; padding: 22rpx; margin-bottom: 14rpx; }
.reading-question-box { margin-bottom: 16rpx; padding-bottom: 14rpx; border-bottom: 1rpx solid rgba(255,255,255,0.5); }
.small-muted { color: #6b8287; font-size: 20rpx; }
.reading-question { display: block; margin-top: 4rpx; color: #2c3e42; font-size: 24rpx; }
.reading-title { color: #3a5358; font-size: 30rpx; font-weight: 600; margin-bottom: 12rpx; }
.tarot-cards { display: flex; flex-direction: column; gap: 10rpx; margin-bottom: 16rpx; }
.tarot-card-item { background: rgba(255,255,255,0.4); border: 1rpx solid rgba(255,255,255,0.6); border-radius: 14rpx; padding: 12rpx; display: flex; gap: 12rpx; align-items: center; }
.mini-card { width: 56rpx; height: 74rpx; border-radius: 10rpx; background: rgba(255,255,255,0.58); border: 1rpx solid rgba(139,168,159,0.4); display: flex; justify-content: center; align-items: center; }
.mini-pos { display: block; color: #6b8287; font-size: 20rpx; }
.mini-name { display: block; color: #3a5358; font-size: 24rpx; margin-top: 2rpx; }
.reading-text { color: #2c3e42; font-size: 24rpx; line-height: 1.7; }
.chat-row { display: flex; margin-bottom: 10rpx; }
.chat-row-user { justify-content: flex-end; }
.chat-row-model { justify-content: flex-start; }
.chat-bubble { max-width: 84%; border-radius: 20rpx; padding: 14rpx; }
.chat-user { background: #8ba89f; color: #fff; }
.chat-text { font-size: 23rpx; line-height: 1.6; }
.chat-input-wrap { display: flex; align-items: center; gap: 10rpx; margin-top: 8rpx; }
.chat-input { flex: 1; height: 72rpx; border-radius: 999rpx; border: 1rpx solid rgba(255,255,255,0.7); background: rgba(255,255,255,0.62); padding: 0 24rpx; font-size: 24rpx; color: #2c3e42; }
.send-btn { width: 62rpx; height: 62rpx; border-radius: 999rpx; background: #8ba89f; color: #fff; display: flex; align-items: center; justify-content: center; }
.pre { white-space: pre-wrap; }
@keyframes spin { to { transform: rotate(360deg); } }
</style>

// src/components/TarotView.tsx
import React, { useState, useEffect, useRef } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { determineTarotSpread, generateTarotReading, generateTarotFollowUp, TarotSpread } from '../lib/gemini';
import ReactMarkdown from 'react-markdown';
import { Clock, Send, ChevronLeft } from 'lucide-react';

const TAROT_DECK = [
  "愚者", "魔术师", "女祭司", "皇后", "皇帝", "教皇",
  "恋人", "战车", "力量", "隐士", "命运之轮", "正义",
  "倒吊人", "死神", "节制", "恶魔", "高塔", "星星",
  "月亮", "太阳", "审判", "世界"
];

type ChatMessage = { role: string, parts: { text: string }[] };

type TarotHistoryItem = {
  id: string;
  date: string;
  question: string;
  spread: TarotSpread;
  cards: string[];
  reading: string;
  chatHistory: ChatMessage[];
};

export default function TarotView() {
  const [view, setView] = useState<'main' | 'history' | 'reading'>('main');
  const [step, setStep] = useState<'question' | 'shuffling' | 'draw'>('question');
  
  const [question, setQuestion] = useState('');
  const [spread, setSpread] = useState<TarotSpread | null>(null);
  const [selectedIndices, setSelectedIndices] = useState<number[]>([]);
  const [drawnCards, setDrawnCards] = useState<string[]>([]);
  
  const [currentReading, setCurrentReading] = useState<TarotHistoryItem | null>(null);
  const [history, setHistory] = useState<TarotHistoryItem[]>([]);
  
  const [followUp, setFollowUp] = useState('');
  const [isChatting, setIsChatting] = useState(false);
  const [isLoading, setIsLoading] = useState(false);
  
  const chatEndRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const saved = localStorage.getItem('tarot_history');
    if (saved) {
      try {
        setHistory(JSON.parse(saved));
      } catch (e) {
        console.error("Failed to parse history", e);
      }
    }
  }, []);

  useEffect(() => {
    if (view === 'reading') {
      chatEndRef.current?.scrollIntoView({ behavior: 'smooth' });
    }
  }, [currentReading?.chatHistory, view]);

  const saveHistory = (newHistory: TarotHistoryItem[]) => {
    setHistory(newHistory);
    localStorage.setItem('tarot_history', JSON.stringify(newHistory));
  };

  const handleStartDraw = async () => {
    if (!question.trim()) return;
    
    setIsLoading(true);
    const spreadResult = await determineTarotSpread(question);
    if (!spreadResult) {
      setIsLoading(false);
      alert("大福暂时无法连接，请稍后再试。");
      return;
    }
    
    setSpread(spreadResult);
    setIsLoading(false);
    
    setStep('shuffling');
    setTimeout(() => {
      setStep('draw');
    }, 2000);
  };

  const handleSelectCard = async (index: number) => {
    if (selectedIndices.includes(index)) return;
    if (!spread) return;

    const newSelected = [...selectedIndices, index];
    setSelectedIndices(newSelected);

    if (newSelected.length === spread.count) {
      const shuffled = [...TAROT_DECK].sort(() => 0.5 - Math.random());
      const finalCards = shuffled.slice(0, spread.count);
      setDrawnCards(finalCards);
      
      setIsLoading(true);
      const result = await generateTarotReading(question, spread, finalCards);
      
      const newItem: TarotHistoryItem = {
        id: Date.now().toString(),
        date: new Date().toLocaleString('zh-CN'),
        question,
        spread,
        cards: finalCards,
        reading: result,
        chatHistory: []
      };
      
      setCurrentReading(newItem);
      saveHistory([newItem, ...history]);
      
      setIsLoading(false);
      setView('reading');
      setStep('question');
      setQuestion('');
      setSpread(null);
      setSelectedIndices([]);
      setDrawnCards([]);
    }
  };

  const handleSendFollowUp = async () => {
    if (!followUp.trim() || !currentReading) return;
    
    const userMsg = followUp;
    setFollowUp('');
    setIsChatting(true);
    
    // Build context for the chat
    const contextHistory: ChatMessage[] = [
      { role: 'user', parts: [{ text: `我之前问了这个问题：“${currentReading.question}”。抽到的牌是：${currentReading.cards.join(', ')}。你的解读是：${currentReading.reading}` }] },
      { role: 'model', parts: [{ text: '我记得。请问你还有什么想深入了解的吗？' }] },
      ...currentReading.chatHistory
    ];
    
    // Optimistically add user message
    const updatedReading = {
      ...currentReading,
      chatHistory: [...currentReading.chatHistory, { role: 'user', parts: [{ text: userMsg }] }]
    };
    setCurrentReading(updatedReading);
    
    const reply = await generateTarotFollowUp(contextHistory, userMsg);
    
    const finalReading = {
      ...updatedReading,
      chatHistory: [...updatedReading.chatHistory, { role: 'model', parts: [{ text: reply }] }]
    };
    
    setCurrentReading(finalReading);
    saveHistory(history.map(h => h.id === finalReading.id ? finalReading : h));
    setIsChatting(false);
  };

  const openHistoryItem = (item: TarotHistoryItem) => {
    setCurrentReading(item);
    setView('reading');
  };

  return (
    <div className="px-6 flex flex-col min-h-full pb-8 flex-1">
      <div className="flex justify-between items-center mt-4 mb-6 shrink-0">
        {view !== 'main' ? (
          <button onClick={() => setView('main')} className="text-gold-600 p-2 -ml-2 hover:bg-white/40 rounded-full transition-colors">
            <ChevronLeft className="w-6 h-6" />
          </button>
        ) : <div className="w-10" />}
        
        <div className="text-center">
          <h2 className="text-xl font-serif text-gold-600">塔罗倾听</h2>
          <p className="text-xs text-text-muted mt-1">让潜意识为你指引方向</p>
        </div>
        
        {view === 'main' ? (
          <button onClick={() => setView('history')} className="text-gold-600 p-2 -mr-2 hover:bg-white/40 rounded-full transition-colors">
            <Clock className="w-5 h-5" />
          </button>
        ) : <div className="w-10" />}
      </div>

      <AnimatePresence mode="wait">
        {view === 'main' && (
          <motion.div
            key="main"
            initial={{ opacity: 0, x: -20 }}
            animate={{ opacity: 1, x: 0 }}
            exit={{ opacity: 0, x: 20 }}
            className="flex-1 flex flex-col justify-center min-h-0"
          >
            {step === 'question' && (
              <div className="glass-panel rounded-3xl p-6 overflow-y-auto">
                <label className="block text-sm text-gold-600 mb-4 font-serif">
                  你现在有什么困惑或心事？
                </label>
                <textarea
                  value={question}
                  onChange={(e) => setQuestion(e.target.value)}
                  placeholder="例如：我最近对工作感到很迷茫，不知道该不该换环境..."
                  className="w-full bg-white/40 border border-white/50 rounded-xl p-4 text-text-main placeholder:text-text-muted/50 focus:outline-none focus:border-gold-500 resize-none h-32"
                />
                <button
                  onClick={handleStartDraw}
                  disabled={!question.trim() || isLoading}
                  className="w-full mt-6 py-3 rounded-xl bg-gold-400 text-white font-medium disabled:opacity-50 disabled:cursor-not-allowed hover:bg-gold-500 transition-colors flex justify-center items-center gap-2 shadow-sm"
                >
                  {isLoading ? (
                    <>
                      <div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                      <span>大福正在思考牌阵...</span>
                    </>
                  ) : (
                    <span>告诉大福</span>
                  )}
                </button>
              </div>
            )}

            {step === 'shuffling' && (
              <div className="flex-1 flex flex-col items-center justify-center gap-8">
                <div className="relative w-24 h-36">
                  {[0, 1, 2].map((i) => (
                    <motion.div
                      key={i}
                      animate={{ 
                        x: [0, (i-1)*20, 0],
                        rotate: [0, (i-1)*10, 0]
                      }}
                      transition={{ repeat: Infinity, duration: 1.5, ease: "easeInOut" }}
                      className="absolute inset-0 bg-white/60 border border-gold-400/30 rounded-xl shadow-md flex items-center justify-center"
                    >
                      <div className="w-16 h-28 border border-gold-400/20 rounded-lg flex items-center justify-center">
                        <span className="text-gold-500/50 text-2xl">✧</span>
                      </div>
                    </motion.div>
                  ))}
                </div>
                <p className="text-sm text-gold-500 font-serif animate-pulse">大福正在为你洗牌...</p>
              </div>
            )}

            {step === 'draw' && spread && (
              <div className="flex-1 flex flex-col items-center gap-6">
                <div className="text-center">
                  <h3 className="text-sm font-serif text-gold-600 mb-1">大福为你选择了：{spread.name}</h3>
                  <p className="text-xs text-text-muted">
                    请深呼吸，凭直觉从下方抽取 <span className="font-bold text-gold-500">{spread.count}</span> 张牌
                    ({selectedIndices.length}/{spread.count})
                  </p>
                </div>
                
                <div className="grid grid-cols-4 gap-3 w-full max-w-[300px] mx-auto">
                  {Array(22).fill(0).map((_, idx) => {
                    const isSelected = selectedIndices.includes(idx);
                    return (
                      <motion.div 
                        key={idx}
                        whileHover={{ scale: isSelected ? 1 : 1.05 }}
                        whileTap={{ scale: 0.95 }}
                        onClick={() => handleSelectCard(idx)}
                        className={`aspect-[2/3] rounded-lg border flex items-center justify-center cursor-pointer transition-all duration-300 ${
                          isSelected 
                            ? 'bg-gold-400/20 border-gold-400 opacity-50' 
                            : 'bg-white/60 border-white/50 shadow-sm hover:border-gold-400/50'
                        }`}
                      >
                        <span className="text-gold-500/30 text-xs">✧</span>
                      </motion.div>
                    );
                  })}
                </div>

                {isLoading && (
                  <div className="flex flex-col items-center gap-2 mt-4">
                    <div className="w-6 h-6 border-2 border-white/50 border-t-gold-400 rounded-full animate-spin" />
                    <p className="text-xs text-gold-500">大福正在解读牌意...</p>
                  </div>
                )}
              </div>
            )}
          </motion.div>
        )}

        {view === 'history' && (
          <motion.div
            key="history"
            initial={{ opacity: 0, x: 20 }}
            animate={{ opacity: 1, x: 0 }}
            exit={{ opacity: 0, x: -20 }}
            className="flex-1 overflow-y-auto pb-4 space-y-4"
          >
            {history.length === 0 ? (
              <div className="text-center text-text-muted mt-10 text-sm">
                暂无占卜记录
              </div>
            ) : (
              history.map(item => (
                <button
                  key={item.id}
                  onClick={() => openHistoryItem(item)}
                  className="w-full text-left glass-panel rounded-2xl p-4 hover:border-gold-400/30 transition-colors"
                >
                  <div className="flex justify-between items-start mb-2">
                    <span className="text-xs text-text-muted">{item.date}</span>
                    <span className="text-xs text-gold-600 bg-gold-400/10 px-2 py-1 rounded-md">{item.spread.name}</span>
                  </div>
                  <p className="text-sm text-text-main line-clamp-2">{item.question}</p>
                </button>
              ))
            )}
          </motion.div>
        )}

        {view === 'reading' && currentReading && (
          <motion.div
            key="reading"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: 20 }}
            className="flex-1 flex flex-col min-h-0"
          >
            <div className="flex-1 overflow-y-auto pb-4 space-y-6 pr-2">
              <div className="glass-panel rounded-3xl p-6">
                <div className="mb-4 pb-4 border-b border-white/40">
                  <p className="text-xs text-text-muted mb-1">你的问题</p>
                  <p className="text-sm text-text-main">{currentReading.question}</p>
                </div>

                <h3 className="text-lg font-serif text-gold-600 mb-4">
                  大福的解读
                </h3>
                
                <div className="flex flex-col gap-3 mb-6">
                  {currentReading.cards.map((card, idx) => (
                    <div key={idx} className="bg-white/30 p-3 rounded-xl border border-white/50 flex items-center gap-3">
                      <div className="w-10 h-14 bg-white/60 rounded border border-gold-400/30 flex items-center justify-center shrink-0">
                        <span className="text-xs">✨</span>
                      </div>
                      <div>
                        <div className="text-xs text-text-muted mb-0.5">{currentReading.spread.positions[idx]}</div>
                        <div className="text-sm font-medium text-gold-600">{card}</div>
                      </div>
                    </div>
                  ))}
                </div>

                <div className="text-sm font-serif leading-relaxed text-text-main whitespace-pre-wrap [&>h1]:text-lg [&>h1]:text-gold-600 [&>h1]:mb-4 [&>h2]:text-base [&>h2]:text-gold-500 [&>h2]:mt-6 [&>h2]:mb-2 [&>p]:mb-4 [&>ul]:list-disc [&>ul]:pl-5 [&>ul]:mb-4 [&>strong]:text-gold-600">
                  <ReactMarkdown>{currentReading.reading}</ReactMarkdown>
                </div>
              </div>

              {/* Chat History */}
              {currentReading.chatHistory.map((msg, idx) => (
                <div key={idx} className={`flex ${msg.role === 'user' ? 'justify-end' : 'justify-start'}`}>
                  <div className={`max-w-[85%] rounded-2xl p-4 text-sm ${
                    msg.role === 'user' 
                      ? 'bg-gold-400 text-white rounded-br-sm shadow-sm' 
                      : 'glass-panel rounded-bl-sm text-text-main'
                  }`}>
                    <ReactMarkdown>{msg.parts[0].text}</ReactMarkdown>
                  </div>
                </div>
              ))}
              
              {isChatting && (
                <div className="flex justify-start">
                  <div className="glass-panel rounded-2xl rounded-bl-sm p-4 text-sm text-gold-500 flex items-center gap-2">
                    <div className="w-3 h-3 border-2 border-white/50 border-t-gold-400 rounded-full animate-spin" />
                    大福正在思考...
                  </div>
                </div>
              )}
              <div ref={chatEndRef} />
            </div>

            {/* Chat Input */}
            <div className="pt-2 pb-2">
              <div className="relative flex items-center">
                <input
                  type="text"
                  value={followUp}
                  onChange={(e) => setFollowUp(e.target.value)}
                  onKeyDown={(e) => e.key === 'Enter' && handleSendFollowUp()}
                  placeholder="继续向大福提问..."
                  className="w-full bg-white/60 border border-white/50 rounded-full py-3 pl-4 pr-12 text-sm text-text-main placeholder:text-text-muted/50 focus:outline-none focus:border-gold-400 shadow-sm"
                />
                <button
                  onClick={handleSendFollowUp}
                  disabled={!followUp.trim() || isChatting}
                  className="absolute right-2 w-8 h-8 rounded-full bg-gold-400 text-white flex items-center justify-center disabled:opacity-50 hover:bg-gold-500 transition-colors"
                >
                  <Send className="w-4 h-4" />
                </button>
              </div>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}
